spring:
  application:
    name: discovery-server

  config:
    import: configserver:http://172.20.10.4:9025
  cloud:
    config:
      fail-fast: true
      username: configserver
      password: cfcv@123